export type Article = { slug: string; title: string; intro: string; shortAnswer: string; whenToCall: string; albertaContext: string; relatedService: string; lastUpdated: string; };
const articles: Article[] = [
{ slug:"why-wont-my-gas-fireplace-turn-on", title:"Why Won't My Gas Fireplace Turn On?", intro:"Startup failures usually come from ignition, pilot, or sensor issues.", shortAnswer:"If reset attempts fail, stop using the fireplace and schedule diagnostics.", whenToCall:"If the unit fails repeatedly or you smell gas, stop use and call.", albertaContext:"Alberta weather swings can expose weak components during seasonal startup.", relatedService:"/services/gas-fireplace-repair", lastUpdated:"May 6, 2026" },
{ slug:"pilot-light-keeps-going-out", title:"Why Does My Gas Fireplace Pilot Light Keep Going Out?", intro:"Frequent pilot outages often indicate airflow, thermocouple, or valve issues.", shortAnswer:"Recurring pilot outages are a warning sign; service prevents deeper wear.", whenToCall:"If relighting does not hold, book repair service.", albertaContext:"Draft patterns in colder months can make pilot issues more obvious.", relatedService:"/services/gas-fireplace-repair", lastUpdated:"May 6, 2026" },
{ slug:"why-is-my-fireplace-flame-weak", title:"Why Is My Gas Fireplace Flame Weak?", intro:"A weak flame can signal burner obstruction, pressure imbalance, or wear.", shortAnswer:"Weak flame should be diagnosed early.", whenToCall:"If flame strength is inconsistent, schedule inspection.", albertaContext:"Seasonal use patterns in Alberta make issues more noticeable in cold snaps.", relatedService:"/services/gas-fireplace-repair", lastUpdated:"May 6, 2026" },
{ slug:"fireplace-smell-when-turned-on", title:"Why Does My Fireplace Smell When I Turn It On?", intro:"Odors may be normal at startup, but persistent smells can indicate service need.", shortAnswer:"Persistent odors should be professionally checked.", whenToCall:"If odor remains after initial operation, call for service.", albertaContext:"Long off-seasons in Alberta can make first-use smells more noticeable.", relatedService:"/services/gas-fireplace-repair", lastUpdated:"May 6, 2026" },
{ slug:"how-often-service-gas-fireplace-alberta", title:"How Often Should a Gas Fireplace Be Serviced in Alberta?", intro:"Regular maintenance helps keep fireplaces safe and reliable through winter.", shortAnswer:"Most households benefit from routine professional service.", whenToCall:"If performance drops or startup becomes unreliable, schedule service.", albertaContext:"Harsh winter demand in Alberta makes proactive service valuable.", relatedService:"/services/gas-fireplace-repair", lastUpdated:"May 6, 2026" }
];
export const listArticles = () => articles;
export const listArticleSlugs = () => articles.map((a) => a.slug);
export const getArticleBySlug = (slug: string) => articles.find((a) => a.slug === slug);